apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demoprod
spec:
  template:
    spec:
      containers:
      - name: demo
        env:
        - name: ENVIRONMENT
          value: prod
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demoprod
spec:
  rules:
  - host: demoprod.eqslearning.com
    http:
      paths:
      - path: /
        backend:
          serviceName: demoprod
          servicePort: 80
